# DATA

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    'Country' : ['India', 'US', 'Japan', 'US', 'Japan'],
    'Age': [44, 34, 46, 35, 23],
    'Salary' : [72000, 65000, 98000, 45000, 43000]
})

df

  Country  Age  Salary
0   India   44   72000
1      US   34   65000
2   Japan   46   98000
3      US   35   45000
4   Japan   23   43000

# LABEL ENCODING

In [3]:
from sklearn.preprocessing import  LabelEncoder

In [4]:
le = LabelEncoder()

In [5]:
df['Country'] = le.fit_transform(df['Country'])
df

   Country  Age  Salary
0        0   44   72000
1        2   34   65000
2        1   46   98000
3        2   35   45000
4        1   23   43000

In [6]:
le.classes_

array(['India', 'Japan', 'US'], dtype=object)

# One Hot Encoding

In [9]:
df = pd.DataFrame({
    'Country' : ['India', 'US', 'Japan', 'US', 'Japan'],
    'Age': [44, 34, 46, 35, 23],
    'Salary' : [72000, 65000, 98000, 45000, 34000]
})

df

  Country  Age  Salary
0   India   44   72000
1      US   34   65000
2   Japan   46   98000
3      US   35   45000
4   Japan   23   34000

In [11]:
X  = df['Country'].values.reshape(-1, 1)
X

<StringArray>
[
['India'],
['US'],
['Japan'],
['US'],
['Japan']
]
Shape: (5, 1), dtype: str

In [12]:
from sklearn.preprocessing import  OneHotEncoder

In [13]:
ohe = OneHotEncoder()
X = ohe.fit_transform(X).toarray()
X

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [14]:
ohe.categories_

[array(['India', 'Japan', 'US'], dtype=object)]

In [15]:
df_ohe = pd.DataFrame(X, columns=[str(i) for i in range(X.shape[1])])

In [16]:
df_ohe

     0    1    2
0  1.0  0.0  0.0
1  0.0  0.0  1.0
2  0.0  1.0  0.0
3  0.0  0.0  1.0
4  0.0  1.0  0.0

In [18]:
df = pd.concat([df_ohe, df],axis=1)
df

     0    1    2 Country  Age  Salary
0  1.0  0.0  0.0   India   44   72000
1  0.0  0.0  1.0      US   34   65000
2  0.0  1.0  0.0   Japan   46   98000
3  0.0  0.0  1.0      US   35   45000
4  0.0  1.0  0.0   Japan   23   34000

In [19]:
df = df.drop(['Country'], axis=1)
df

     0    1    2  Age  Salary
0  1.0  0.0  0.0   44   72000
1  0.0  0.0  1.0   34   65000
2  0.0  1.0  0.0   46   98000
3  0.0  0.0  1.0   35   45000
4  0.0  1.0  0.0   23   34000