## KLASIFIKASI Menggunakan Metode Naive Bayes

## Import Library

In [54]:
import pandas as pd
import numpy as np


from sklearn.model_selection import train_test_split # <- spliting data / pembagian data
from sklearn.preprocessing import LabelEncoder #<- mengkonfersi data string menjadi label numrik
from sklearn.preprocessing import StandardScaler # <- mengsekala data numrik
from sklearn.naive_bayes import  GaussianNB # <- algoritma / Metode
from sklearn.metrics import confusion_matrix # <- menguji kinerja model
from sklearn.metrics import classification_report # <- evaluasi
from sklearn.metrics import  accuracy_score # <- evaluasi

## Baca Data

In [55]:
df_1 = pd.read_csv("dataset_customer_churn_label_string.csv")
df_1.head() #<- menampilkan 5 data taeratas

,customer_id,age,city,tenure_months,plan_type,monthly_bill,usage_hours,support_tickets,churn
0,1,56,Tangerang,52,Basic,428,76,14,Tidak Bertahan
1,2,38,Jakarta,24,Premium,210,57,5,Bertahan
2,3,19,Surabaya,30,Basic,373,68,1,Bertahan
3,4,38,Bandung,33,Basic,393,93,5,Bertahan
4,5,44,Tangerang,59,Basic,249,64,11,Bertahan

In [56]:
df_1.info() # <- mengatahui informasi terkait dataset

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customer_id      1000 non-null   int64
 1   age              1000 non-null   int64
 2   city             1000 non-null   str
 3   tenure_months    1000 non-null   int64
 4   plan_type        1000 non-null   str
 5   monthly_bill     1000 non-null   int64
 6   usage_hours      1000 non-null   int64
 7   support_tickets  1000 non-null   int64
 8   churn            1000 non-null   str
dtypes: int64(6), str(3)
memory usage: 70.4 KB

In [57]:
df_1.empty # < - mengetahui apakah ada data kosong

False

### Process Label Encoding

ubah tipe data label yang tadinya str menjadi numrik

In [58]:
numrik = LabelEncoder() 

df_1['churn'] = numrik.fit_transform(df_1['churn'])

df_1['city'] = numrik.fit_transform(df_1['city'])

df_1['plan_type'] = numrik.fit_transform(df_1['plan_type'])
df_1.head()

,customer_id,age,city,tenure_months,plan_type,monthly_bill,usage_hours,support_tickets,churn
0,1,56,6,52,0,428,76,14,1
1,2,38,3,24,1,210,57,5,0
2,3,19,5,30,0,373,68,1,0
3,4,38,0,33,0,393,93,5,0
4,5,44,6,59,0,249,64,11,0

### Data sudah berubah dimana yagn tadinya string sekarang int

## Menetukan X dan Y

In [59]:
x = df_1.iloc[:, :-1].values
y = df_1.iloc[:, -1].values

In [60]:
x

array([[   1,   56,    6, ...,  428,   76,   14],
       [   2,   38,    3, ...,  210,   57,    5],
       [   3,   19,    5, ...,  373,   68,    1],
       ...,
       [ 998,   50,    4, ...,  460,   52,    5],
       [ 999,   44,    1, ...,  219,   65,   10],
       [1000,   48,    6, ...,  444,   39,   10]], shape=(1000, 8))

In [61]:
y

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Spiliting Data

In [62]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=123)

print("X Train = ", len(x_train))
print("X Test = ", len(x_test))
print("Y Train = ", len(y_train))
print("Y Test = ", len(y_test))

X Train =  800
X Test =  200
Y Train =  800
Y Test =  200

### Pengskalaan Nilai

In [63]:
sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [65]:
x_train

array([[ 0.0515938 ,  0.77912942, -0.03179685, ..., -0.44625829,
         1.40560439,  0.93090378],
       [ 0.65626661, -0.30840728, -0.03179685, ...,  0.92447328,
        -0.5260595 ,  1.38947707],
       [ 1.7467748 ,  0.63412453,  0.4669773 , ...,  1.38679103,
         0.02063782, -0.44481609],
       ...,
       [-0.40278462,  1.14164166,  0.4669773 , ..., -0.7058051 ,
        -1.40077523, -0.44481609],
       [-0.46220333,  0.19910985,  0.96575145, ..., -0.52736667,
         0.20287027,  1.16019043],
       [ 0.04460336,  0.34411474, -0.530571  , ...,  1.7031137 ,
        -0.34382706,  0.93090378]], shape=(800, 8))

In [66]:
x_test

array([[-1.26454394,  0.19530663,  1.44787362, ..., -1.43779388,
         0.65284993,  1.34919328],
       [-1.02338814, -1.68264172,  1.44787362, ...,  0.92524212,
        -0.43765663, -0.49113856],
       [-1.5358442 , -0.25540098,  1.44787362, ...,  0.82432955,
        -0.58305751,  0.19898588],
       ...,
       [ 0.4972331 ,  1.6976653 , -0.92568969, ...,  0.37863237,
         0.72555037, -0.72118004],
       [-0.99994244,  1.54742944, -0.92568969, ...,  1.04297345,
         0.94365168, -0.72118004],
       [-0.42719744,  1.6976653 , -1.40040236, ..., -0.87436537,
        -0.1832051 , -0.26109708]], shape=(200, 8))

In [68]:
y_train

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [69]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0])

## Clasifikasi Model

In [71]:
klasifikasi = GaussianNB()

In [73]:
klasifikasi.fit(x_train, y_train)

GaussianNB()

In [75]:
y_predict = klasifikasi.predict(x_test)
y_predict

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0])

In [76]:
klasifikasi.predict_proba(x_test)

array([[9.74850112e-01, 2.51498882e-02],
       [8.11053127e-01, 1.88946873e-01],
       [7.26303615e-01, 2.73696385e-01],
       [9.22496088e-01, 7.75039123e-02],
       [9.57108956e-01, 4.28910437e-02],
       [9.39247043e-01, 6.07529567e-02],
       [9.09103924e-01, 9.08960756e-02],
       [9.97755827e-01, 2.24417294e-03],
       [9.85193147e-01, 1.48068527e-02],
       [7.20481759e-01, 2.79518241e-01],
       [9.83922497e-01, 1.60775034e-02],
       [9.89121648e-01, 1.08783517e-02],
       [9.49630940e-01, 5.03690600e-02],
       [9.95832028e-01, 4.16797200e-03],
       [9.29346164e-01, 7.06538362e-02],
       [9.78713037e-01, 2.12869626e-02],
       [8.86021710e-01, 1.13978290e-01],
       [9.30626118e-01, 6.93738825e-02],
       [9.84525311e-01, 1.54746892e-02],
       [9.90604859e-01, 9.39514104e-03],
       [4.87792440e-01, 5.12207560e-01],
       [9.86757512e-01, 1.32424876e-02],
       [9.93761999e-01, 6.23800118e-03],
       [9.44330148e-01, 5.56698521e-02],
       [5.29341986e-01, 4.70658014e-01],
       [9.63735714e-01, 3.62642859e-02],
       [9.97352452e-01, 2.64754784e-03],
       [8.77940042e-01, 1.22059958e-01],
       [9.97940904e-01, 2.05909553e-03],
       [9.98191035e-01, 1.80896471e-03],
       [9.93352451e-01, 6.64754868e-03],
       [9.85340651e-01, 1.46593493e-02],
       [7.92931890e-01, 2.07068110e-01],
       [9.44888866e-01, 5.51111343e-02],
       [8.86159054e-01, 1.13840946e-01],
       [9.82351097e-01, 1.76489025e-02],
       [9.93110841e-01, 6.88915857e-03],
       [9.20119955e-01, 7.98800448e-02],
       [9.13981486e-01, 8.60185140e-02],
       [9.84686927e-01, 1.53130734e-02],
       [9.42798532e-01, 5.72014677e-02],
       [9.99173323e-01, 8.26677237e-04],
       [9.93400637e-01, 6.59936296e-03],
       [9.45373789e-01, 5.46262105e-02],
       [9.83720802e-01, 1.62791975e-02],
       [9.18261559e-01, 8.17384412e-02],
       [9.99586235e-01, 4.13765434e-04],
       [9.77496382e-01, 2.25036183e-02],
       [9.20103422e-01, 7.98965776e-02],
       [5.33932758e-01, 4.66067242e-01],
       [5.45244875e-01, 4.54755125e-01],
       [6.91043741e-01, 3.08956259e-01],
       [8.63125003e-01, 1.36874997e-01],
       [9.29096461e-01, 7.09035394e-02],
       [9.95164095e-01, 4.83590536e-03],
       [9.63221725e-01, 3.67782748e-02],
       [8.47890826e-01, 1.52109174e-01],
       [9.06709945e-01, 9.32900554e-02],
       [9.98438403e-01, 1.56159728e-03],
       [9.91440362e-01, 8.55963792e-03],
       [9.99154140e-01, 8.45860356e-04],
       [8.76755994e-01, 1.23244006e-01],
       [9.94221577e-01, 5.77842282e-03],
       [9.91118593e-01, 8.88140712e-03],
       [1.28252895e-01, 8.71747105e-01],
       [6.88027653e-01, 3.11972347e-01],
       [9.88892896e-01, 1.11071043e-02],
       [9.84058685e-01, 1.59413149e-02],
       [9.88557842e-01, 1.14421580e-02],
       [9.86427460e-01, 1.35725403e-02],
       [8.86555723e-01, 1.13444277e-01],
       [5.30298668e-01, 4.69701332e-01],
       [7.70877708e-01, 2.29122292e-01],
       [9.78012448e-01, 2.19875518e-02],
       [5.77026194e-01, 4.22973806e-01],
       [9.69317840e-01, 3.06821597e-02],
       [9.87419595e-01, 1.25804046e-02],
       [9.97384731e-01, 2.61526935e-03],
       [8.33557286e-01, 1.66442714e-01],
       [9.62423744e-01, 3.75762559e-02],
       [8.56329295e-01, 1.43670705e-01],
       [9.86633168e-01, 1.33668322e-02],
       [9.89905214e-01, 1.00947856e-02],
       [8.85679479e-01, 1.14320521e-01],
       [9.75589823e-01, 2.44101765e-02],
       [9.64656627e-01, 3.53433728e-02],
       [9.54869726e-01, 4.51302743e-02],
       [8.99126372e-01, 1.00873628e-01],
       [9.73391670e-01, 2.66083298e-02],
       [7.63994062e-01, 2.36005938e-01],
       [8.12068797e-01, 1.87931203e-01],
       [9.59986984e-01, 4.00130161e-02],
       [9.50424679e-01, 4.95753212e-02],
       [9.93091746e-01, 6.90825414e-03],
       [7.22655768e-01, 2.77344232e-01],
       [8.90975652e-01, 1.09024348e-01],
       [6.86982827e-01, 3.13017173e-01],
       [9.98674739e-01, 1.32526124e-03],
       [9.72127870e-01, 2.78721299e-02],
       [6.69248711e-01, 3.30751289e-01],
       [9.28391587e-01, 7.16084135e-02],
       [9.99474396e-01, 5.25604110e-04],
       [9.64980686e-01, 3.50193144e-02],
       [8.91641662e-01, 1.08358338e-01],
       [9.60925078e-01, 3.90749223e-02],
       [9.17977352e-01, 8.20226483e-02],
       [9.96442862e-01, 3.55713754e-03],
       [7.74702843e-01, 2.25297157e-01],
       [8.87179645e-01, 1.12820355e-01],
       [8.33109197e-01, 1.66890803e-01],
       [9.13103961e-01, 8.68960390e-02],
       [9.97430336e-01, 2.56966353e-03],
       [9.72960720e-01, 2.70392803e-02],
       [5.45156163e-01, 4.54843837e-01],
       [7.53074255e-01, 2.46925745e-01],
       [9.96461839e-01, 3.53816129e-03],
       [9.82006425e-01, 1.79935752e-02],
       [4.52769507e-01, 5.47230493e-01],
       [8.31087025e-01, 1.68912975e-01],
       [7.38987262e-01, 2.61012738e-01],
       [9.86845466e-01, 1.31545339e-02],
       [9.99150655e-01, 8.49344899e-04],
       [9.80449750e-01, 1.95502502e-02],
       [9.98024091e-01, 1.97590931e-03],
       [9.94297566e-01, 5.70243387e-03],
       [6.71539325e-01, 3.28460675e-01],
       [9.49850512e-01, 5.01494875e-02],
       [9.90523124e-01, 9.47687564e-03],
       [9.98548233e-01, 1.45176719e-03],
       [8.95633343e-01, 1.04366657e-01],
       [9.90401278e-01, 9.59872214e-03],
       [9.73395974e-01, 2.66040262e-02],
       [9.88094559e-01, 1.19054415e-02],
       [8.75353129e-01, 1.24646871e-01],
       [9.42028511e-01, 5.79714893e-02],
       [9.97394585e-01, 2.60541532e-03],
       [4.95822507e-01, 5.04177493e-01],
       [9.67157509e-01, 3.28424914e-02],
       [9.93248903e-01, 6.75109709e-03],
       [8.49392390e-01, 1.50607610e-01],
       [7.83385970e-01, 2.16614030e-01],
       [3.19059771e-01, 6.80940229e-01],
       [9.71387915e-01, 2.86120853e-02],
       [9.90122016e-01, 9.87798361e-03],
       [7.03528780e-01, 2.96471220e-01],
       [8.68132950e-01, 1.31867050e-01],
       [9.86612686e-01, 1.33873139e-02],
       [9.41135121e-01, 5.88648793e-02],
       [9.98858419e-01, 1.14158120e-03],
       [9.99428466e-01, 5.71534422e-04],
       [9.99220360e-01, 7.79640476e-04],
       [9.95386120e-01, 4.61387975e-03],
       [9.02396406e-01, 9.76035938e-02],
       [8.53726082e-01, 1.46273918e-01],
       [9.27264241e-01, 7.27357594e-02],
       [9.58694524e-01, 4.13054758e-02],
       [9.88705327e-01, 1.12946733e-02],
       [9.98161117e-02, 9.00183888e-01],
       [9.64038502e-01, 3.59614975e-02],
       [9.75343971e-01, 2.46560293e-02],
       [9.77113556e-01, 2.28864437e-02],
       [8.55580248e-01, 1.44419752e-01],
       [2.73808839e-01, 7.26191161e-01],
       [9.47137629e-01, 5.28623707e-02],
       [9.80816504e-01, 1.91834961e-02],
       [9.85442864e-01, 1.45571361e-02],
       [8.09336611e-01, 1.90663389e-01],
       [7.92665763e-01, 2.07334237e-01],
       [9.97898278e-01, 2.10172188e-03],
       [9.71515591e-01, 2.84844092e-02],
       [9.63529561e-01, 3.64704395e-02],
       [9.88671565e-01, 1.13284353e-02],
       [7.13563246e-01, 2.86436754e-01],
       [9.87353083e-01, 1.26469175e-02],
       [9.91432504e-01, 8.56749650e-03],
       [8.39728953e-01, 1.60271047e-01],
       [4.66611225e-01, 5.33388775e-01],
       [9.97977235e-01, 2.02276546e-03],
       [9.60411217e-01, 3.95887833e-02],
       [3.43286489e-01, 6.56713511e-01],
       [9.85384705e-01, 1.46152946e-02],
       [9.91284245e-01, 8.71575512e-03],
       [9.42289413e-01, 5.77105866e-02],
       [9.96899253e-01, 3.10074716e-03],
       [9.56733972e-01, 4.32660282e-02],
       [8.05275326e-01, 1.94724674e-01],
       [8.03306800e-01, 1.96693200e-01],
       [8.72602891e-01, 1.27397109e-01],
       [7.21035328e-01, 2.78964672e-01],
       [6.76833374e-01, 3.23166626e-01],
       [9.69487413e-01, 3.05125874e-02],
       [3.40704753e-01, 6.59295247e-01],
       [9.98166708e-01, 1.83329236e-03],
       [9.79535385e-01, 2.04646147e-02],
       [8.99687812e-01, 1.00312188e-01],
       [9.98825909e-01, 1.17409117e-03],
       [9.28172675e-01, 7.18273249e-02],
       [9.95770709e-01, 4.22929078e-03],
       [9.91135592e-01, 8.86440777e-03],
       [9.91256539e-01, 8.74346064e-03]])

## EVALUASI

In [77]:
cm = confusion_matrix(y_test,y_predict)
print(cm)

[[174   1]
 [ 16   9]]

In [80]:
akurasi = classification_report(y_test, y_predict)
print(akurasi)

              precision    recall  f1-score   support

           0       0.92      0.99      0.95       175
           1       0.90      0.36      0.51        25

    accuracy                           0.92       200
   macro avg       0.91      0.68      0.73       200
weighted avg       0.91      0.92      0.90       200

In [82]:
akurasi = accuracy_score(y_test, y_predict)
print("Tingkat Akurasi : %d Persen"%(akurasi*100))

Tingkat Akurasi : 91 Persen